name: 'Testing config import module'
type: module
description: 'Tests install profiles in the config importer.'
# version: VERSION
package: Testing

# Information added by Drupal.org packaging script on 2025-11-12
version: '10.5.6'
project: 'drupal'
datestamp: 1762990926
